softeerbootcamp4th/Team7-HybridJGS-FE

client/package.json
client/src/components/Toggle/index.stories.tsx
client/src/components/Toggle/index.tsx
client/yarn.lock

https://github.com/user-attachments/assets/95f9307b-66c9-419f-a493-19d4d4aeaa83
close #3
Toggle 컴포넌트의 애니메이션을 위해 컴포넌트를 클릭 시 현재 선택된 텍스트의 width를 가져와서 black background의 width에 세팅해주기로 했다.
|우리가 원하는 UI|실제로 첫 렌더링 시 적용되는 UI|
|---|---|
|![image](https://github.com/user-attachments/assets/ad7f104f-51b9-4fdc-9307-64849e334d1a)|![image](https://github.com/user-attachments/assets/93e35718-2fcd-418b-8f5c-9d2b9042992a)|
첫 렌더링 시 왼쪽과 같이 ‘Now’ 텍스트에 맞게 black background 크기가 맞춰져야하는데, 실제로는 오른쪽과 같이 약간 작게 width가 잡히는 경향이 있었다.
이유를 생각해보는데, 첫 렌더링 시에만 저런 width 오차가 발생하는 것으로 보아 폰트를 가져오기 전에 width가 잘못 설정된 것 같았다.
```tsx
useEffect(() => {
if (document.fonts) {
document.fonts.ready.then(calculateTextWidth);
} else {
window.addEventListener("load", calculateTextWidth);
return () => window.removeEventListener("load", …
```

[Feat] Toggle 컴포넌트 구현

---

client/tsconfig.app.json

없음
vite.config 파일 뿐만 아니라 tsconfig에도 alias를 적용해줘야 typescript에서 alias 인식이 가능하다.

[Fix] tsconfig에 alias 선언 형식 추가

---

client/public/assets/icon/arrow-down.svg
client/src/components/Scroll/index.stories.tsx
client/src/components/Scroll/index.tsx

|light|dark|
|---|---|
|<img width="241" alt="스크린샷 2024-07-25 오후 6 31 27" src="https://github.com/user-attachments/assets/a771fe5f-ecd8-450f-b48d-64f27aa7f678">|<img width="270" alt="스크린샷 2024-07-25 오후 6 31 34" src="https://github.com/user-attachments/assets/e6b0f3af-4c2d-4dd9-9887-fc19d7b67c28">|
close #36
원래는 그냥 텍스트만 받게 하려고 했는데, 문제는 내부 텍스트가 하나의 스타일이 아니라 아래와 같이 weight가 여러 개라서 텍스트만 받기에는 무리가 있다고 판단했다.
그래서 부득이하게,,, 사용할 때 텍스트 스타일을 직접 주입해서 사용할 수 있도록 했다.
```tsx
<Scroll {...args} type="dark">
<span className="h-body-2-regular">
이벤트에 대해 궁금하다면 <span className="h-body-2-bold">스크롤</span>해 보세요
</span>
</Scroll>
```

[Feat] Scroll 컴포넌트 구현

---

client/src/components/Tooltip/index.stories.tsx
client/src/components/Tooltip/index.tsx

close #54
기존에 정의한 tooltip positionPercent props가 실 서비스에서 호환되지 않는 문제가 있어서 position을 left, center, right로 제한해서 호환되게 수정했다.

[Fix] tooltip position prop를 left, center, right로 제한

---

client/src/components/CTAButton/index.stories.tsx
client/src/components/CTAButton/index.tsx
client/src/pages/Main/index.tsx

https://github.com/user-attachments/assets/36652599-0d89-48f4-9f15-09cf8dd214e9
close #15 
arrowIcon과 shareIcon 두 가지를 따로 사용하기 때문에 hasIcon 대신 두 개의 Props를 분리해주었다.
```tsx
const content = (
<>
{label}
{hasArrowIcon && <ArrowIcon stroke={strokeColor} />}
{hasShareIcon && <ShareIcon stroke={strokeColor} />}
</>
);
```
CTA Button 컴포넌트 내부에서 링크를 연동하는 작업을 해주어야 했는데, 문제는 우리 프로젝트 내부에서 라우팅되는 것과 외부 링크와 연동되는 부분을 따로 분리해주어야 했다.
그래서 처음에는 그냥 react-router-dom의 Link 컴포넌트를 사용하여 작업해주었는데, 외부 링크 연동하는 작업에서는 새 창을 열도록 하고 싶었다. 근데 Link 컴포넌트 자체에서는 새 창 열기 기능을 제공해주지 않았다. 그래서 두 가지로 분기 처리를 해주기로 했다. 우선 아래와 같이 props로 받은 url의 접두에 프로토콜 “http” 또는 “https” 이 붙어있는지 확인하도록 해주었다.
```tsx
const isExternalLink = url && (url.startsWith("http://") || url.startsWith("https://"));
```
그래서 만약 isExternalLink가 true일 때는 외부 링크로 접속해야 하므로 a 태그를 …

[Fix] CTA Button 기능 추가

---

client/src/components/Header/index.tsx

https://github.com/user-attachments/assets/a655f43b-8f5e-4f81-bc65-5abcd16fd814
close #73

[Feat] 헤더 클릭 라우팅 추가 및 수정

---

client/src/components/Header/index.tsx
client/src/components/Input/index.tsx
client/src/components/PopUp/index.tsx
client/src/components/Toast/index.tsx
client/src/features/Lottery/Headline.tsx
client/src/features/Lottery/ShortCut.tsx
client/src/hooks/usePopup.tsx
client/src/pages/Lottery/index.tsx

https://github.com/user-attachments/assets/bb82674d-a87e-4c4e-9d28-74c084446ea1
https://github.com/user-attachments/assets/9e1ce2ae-f2d7-443d-9b80-a96558827fd2
close #72 
처음에는 `overflow: hidden`를 모달 영역에 줘서 스크롤 방지가 안 되는 문제가 있었다. 팝업이 떠 있을 때 스크롤 방지를 하려면 body 자체에 스크롤 방지 옵션을 넣어줘야 제대로 스크롤 방지가 된다. ㅎ
```tsx
const handleClosePopup = () => {
document.body.style.overflow = "unset";
setIsVisible(false);
};
const handleOpenPopup = () => {
document.body.style.overflow = "hidden";
setIsVisible(true);
};
```
그래서 처음에 요렇게 해줬는데, 문제가 있었다. close 로직은 dim 영역을 클릭하게나 X 버튼을 클릭했을때만 호출되는 로직이라 제대로 제출해서 confirm을 호출했을 때는 overflow hidden이 그대로 남아있어서 스크롤이 막히는 게 문제였다.
```tsx
useEffect(() => {
if (!isVisible) {
document.body.style.overflow = "unset";
}
}, [isVisible]);
const handleOpenPopup = () => { …
```

[Feat] 추첨 페이지 모달 연결

---

client/src/components/Tooltip/index.tsx

https://github.com/user-attachments/assets/cffb8574-2d1a-4103-b3e4-c2b75955359e
close #87
기존에 툴팁이 위치를 제대로 못 잡는 문제가 있었는데, 스크롤의 기준을 `window.scrollY`, `window.scrollX`로 잡다보니까 문서 전체의 렌더링이 완벽하게 되지 않은 시점에서 윈도우 scroll이 계산되면서 발생하는 문제 같았습니다.
그래서 window 기준 스크롤에서 트리거 기준 scroll을 계산하는 걸로 바꾸었습니다. (triggerRef.current.scrollLeft와 triggerRef.current.scrollTop은 요소의 스크롤을 직접 참조해서 정확히 스크롤 위치 가져옴)

[Fix] 툴팁 위치 오류 수정

---

client/src/features/CasperCustom/CasperFlipCard.tsx
client/src/features/CasperShowCase/TransitionCasperCards.tsx
client/src/hooks/useLazyLoading.ts

https://github.com/user-attachments/assets/b6c12340-f965-4d61-a30e-7da7f4dceb08
close #95
https://github.com/user-attachments/assets/7fbd1e54-56b4-4050-90fa-c12b194ef02c
카드에 hover가 될 때마다 카드에 flip 애니메이션이 발생해야하는데, 이때 관련 없는 다른 컴포넌트들에도 리렌더링이 발생하면서 flip 애니메이션이 버벅이는 현상이 있었다.
문제는 리스트를 뿌려주는 컴포넌트에서 hover 된 시점의 x를 저장하고 업데이트 하는 로직을 담당하고 있는데, 그렇다 보니 hover 될 때마다 상태가 바뀌게 되었고, 자식 컴포넌트인 CasperFlipCard 컴포넌트의 리렌더링도 발생한 것이다.
```tsx
function CasperFlipCard({ size, card, isFlipped }: CasperFlipCardProps) {
...
}
export default memo(CasperFlipCard);
```
react에서 제공하는 `memo`를 사용해서 props가 변할 때만 리렌더링이 발생하게 수정했다.
https://github.com/user-attachments/assets/94bc74b8-7da0-492d-aa08-2ab6c4968967
https://github.com/user-attachments/assets/45763c51-cec0-4d8d-adfe-fdddb0bba910
showcase 화면으로 넘어갈때 시간이 너무 많이 걸리는 문제가 있었다. …

[Fix] 캐스퍼 쇼케이스 화면 로딩 오래 걸리는 오류 수정

---

client/.gitignore
client/src/components/CTAButton/index.tsx
client/src/components/PopUp/index.tsx

https://github.com/user-attachments/assets/2d776859-8abb-4d29-9e69-d9614e8e61a7
close #110
처음에는 submit이 제대로 동작하지 않았다.
form 액션이 실행되지 않았는데, 찾아보니 form 안에 button이 두 개 있는 경우 submit 행위를 하는 버튼에만 type을 명시해줄 것이 아니라 다른 버튼에도 type="button"을 명시해줘야 제대로 동작한다.

[Feat] Popup Submit 작동 추가

---

client/src/constants/cookie.ts
client/src/features/CasperCustom/CasperCustomForm.tsx
client/src/hooks/useFetch.ts
client/src/pages/ErrorElement/index.tsx

close #140
오류 발생 시 나오는 ErrorElement에서 navigate가 동작 안 하는 문제가 있었습니다. 오류가 발생하는 경우 렌더링이 회복되지 못해서 navigate가 되지 않는 것으로 파악해, 돌아가기를 클릭하는 경우 아예 페이지 새로고침을 하도록 구현했습니다.

[Fix] 메인 페이지 오류 수정

---

admin/src/apis/authAPI.ts
admin/src/hooks/useFetch.ts
admin/src/pages/Login/index.tsx
admin/src/utils/fetchWithTimeout.ts
client/src/utils/fetchWithTimeout.ts

close #145
기존에 로그인이 실패해도 token이 undefined로 들어가고 메인 페이지로 접속이 가능한 문제가 있었습니다. 원인은 fetch에 있었는데, fetch는 오류 응답을 자동으로 예외로 처리하지 않습니다. fetch API는 HTTP 오류 상태 코드(예: 400, 404, 500)를 네트워크 오류로 취급하지 않고, 성공적인 응답으로 간주해서 error를 throw하지 않습니다.
따라서 일반적으로 발생하는 오류를 try/catch하는 코드 뿐만 아니라 status code를 확인하는 코드가 필요했습니다.
status를 확인하기 위해서 respones.ok(200-299 사이의 status를 정상적인 응답으로 간주)를 사용했습니다.
```tsx
export async function fetchWithTimeout(url: string, options: RequestInit = {}, timeout = 5000) {
const controller = new AbortController();
const id = setTimeout(() => controller.abort(), timeout);
options.signal = controller.signal;
const response = await fetch(url, options);
clearTimeout(id);
if (!response.ok) {
throw new Error(response.statusText);
}
return response;
}
```
위와 같이 response.ok가 아닌 경우 error를 throw하게 해서 …

[Feat] 어드민 API 예외처리

---

client/src/features/CasperCustom/Battery.tsx
client/src/features/CasperCustom/CasperCustomFinish.tsx
client/src/hooks/useFetch.ts
client/src/pages/CasperShowCase/index.tsx
client/src/utils/writeClipboard.ts

https://github.com/user-attachments/assets/92bb30dd-3180-4445-a1e0-09900e07f60a
close #154
제가 캐스퍼 봇 생성 완료 후 나타나는 화면에서의 공유 버튼에만 API 연동을 해줬길래 쇼케이스 페이지의 공유 버튼에도 link share API 연동을 추가했습니당,,😅

[Feat] 캐스퍼 쇼케이스에서 공유 링크 구현

---

client/src/features/Main/Lottery.tsx
client/src/features/RushGame/RushGameComponents/RushBar.tsx
client/src/features/RushGame/RushGameComponents/RushCardCurrentRatio.tsx

https://github.com/user-attachments/assets/876fa02d-ce05-43bd-89c0-be1057ddae65
https://github.com/user-attachments/assets/28418cb5-ab2f-4f33-a9bf-e21fc1d9e0a0
close #166

[Fix] 전체적인 UI 오류 수정

---

client/src/constants/Rush/rushCard.ts
client/src/features/RushGame/RushGameComponents/RushCardComparison.tsx
client/src/utils/getRandomCardColors.ts

close #167 
```tsx
while (rightColorIdx === leftColorIdx) {
rightColorIdx = Math.floor(Math.random() * colors.length);
}
```
두 카드의 색상이 겹치지 않도록 하기 위해서, 만약 동일한 색이 나올 경우 동일한 색이 나오지 않을 때까지 오른쪽 카드를 랜덤으로 계속 돌려주도록 구현했습니다.

[Feat] RushCard 색상 랜덤 기능 구현

---

.github/workflows/client_push.yml
client/src/pages/RushGame/index.tsx

https://github.com/user-attachments/assets/5d447862-e56c-4d6e-9c92-86c793fd5f32
close #165  
이거 workflow 이렇게 작성하는게 맞는 건지 잘 모르겠네용ㅠㅠ 검토 부탁드립니다..!!

[Feat] 선착순 밸런스 게임 이벤트 공유 링크 연동

---

admin/src/apis/lotteryAPI.ts
admin/src/components/Loading/index.tsx
admin/src/components/Suspense/index.tsx
admin/src/components/TimePicker/index.tsx
admin/src/constants/common.ts
admin/src/hooks/useFetch.ts
admin/src/hooks/useInfiniteFetch.ts
admin/src/pages/LotteryParticipantList/index.tsx
admin/src/pages/LotteryWinner/index.tsx
admin/src/pages/LotteryWinnerList/index.tsx
admin/src/pages/RushWinnerList/index.tsx
admin/src/types/lotteryApi.ts
admin/src/utils/fetchWithTimeout.ts
admin/src/utils/getTimeDifference.ts

close #184
이미 추첨한 이력이 있는 경우 추첨 API를 호출하면 오류가 발생합니다. 오류를 없애기 위해서 추첨한 이력이 있는 경우 이전 추첨 이력을 삭제하고 다시 추첨 API를 호출하도록 수정했습니다.

[Fix] 어드민 오류 수정

---

client/src/features/RushGame/RushGameSections/FinalResult.tsx

(없음)
close #192 
```tsx
function formatNumber(value?: number): string {
if (value === undefined || value === null) return "";
return value.toLocaleString("en-US");
}
const formattedRank = formatNumber(rank);
const formattedTotalParticipants = formatNumber(totalParticipants);
```
최종 결과를 보여주는 화면에서 rank, totalParticipants가 null일 경우가 존재하지 않는다고 생각했다.
실제로 타입을 다음과 같이 정의해놨고 타입 추론도 number | undefined였기 때문이다.
```tsx
export interface GetRushResultResponse {
optionId?: CardOption;
isWinner?: boolean;
leftOption: number;
rightOption: number;
rank?: number;
totalParticipants?: number;
}
```
근데 보아하니 두 값들을 가져오는 resultData 자체가 null일 가능성이 존재했다. 
따라서 formatNumber 함수의 value 부분에 null도 추가로 처리해주었다.

[Fix] 선착순 미참여시 최종 결과 페이지 접근 오류

---

client/src/features/RushGame/RushGameComponents/RushCardCurrentRatio.tsx
client/src/features/RushGame/RushGameSections/SelectedCard.tsx
client/src/hooks/RushGame/useFetchRushBalance.ts
client/src/hooks/RushGame/useFetchRushUserParticipationStatus.ts
client/src/hooks/useFetch.ts

https://github.com/user-attachments/assets/724cab7a-690d-4da6-8ba3-90dd4e98dc40
https://github.com/user-attachments/assets/12c63cbc-9f03-40ba-8215-df6d42cad1d6
close #198 
요청을 보낼 때 pending이 3~4개씩 쌓이는 문제가 있었다. 
사실 다시 영상을 촬영하니 제대로 확인이 되지는 않았지만, 안정성을 위해 useFetch 훅에서 isLoading 상태를 추가하여, 요청이 완전히 반환 시에 true로 반환하고, 새로고침 버튼 throttle 로직에 조건문으로 추가해주었다.
따라서 요청이 완전히 반환되었을 때 다시 balance API 요청을 보낼 수 있도록 해주었다.

[Fix] 응답 완전히 반환 시 요청 보낼 수 있도록 isLoading 추가

---

client/src/features/CasperCustom/CustomProcess/CasperCustomFinish.tsx

close #201
다른 탭에서 캐스퍼 봇 만들기를 했을 때 기존 탭에 있던 cookie의 token이 변경되면서 getApplyCount 요청이 가게 됩니다. 그런데 이때 token이 아직 응모하지 않은 사용자의 token으로 바뀌면서 응모하지 않은 사용자라는 오류가 발생했습니다. 
따라서 dependency에서 cookie를 삭제해서 cookie가 바뀌어도 요청이 다시 발생하지 않게 수정했습니다.

[Fix] getApplyCount dependency 수정

---

client/src/features/RushGame/RushGameComponents/RushCardComparison.tsx

https://github.com/user-attachments/assets/a75452e5-d8ce-454e-90e2-ec4274c2ea68
https://github.com/user-attachments/assets/649fc73c-31d5-4a50-a67b-287ed35ac39e
close #200 
카드 옵션 선택 시 카드 옵션 연타를 계속 하면 post 보낼 때 409 오류가 뜬다.
카드 연타할 경우 POST가 두 번 보내져서 이미 요청한 사용자에 대해서 계속 요청 보내지는 오류 발생하는 것이었다.
throttle 걸어줘서 POST 요청을 1초 정도 딜레이 줘서 요청이 한 번만 가도록 수정했다.
수정 후 몇 번이나 테스트했는데 409 오류는 발생하지 않았다. 
우연히 요청을 한 번밖에 못보낸 건지는 모르겠지만 우선 안전성을 위해 처리해뒀다.
```tsx
const [throttle, setThrottle] = useState<boolean>(false);
const {
data: postSelectedRushOptionResponse,
isSuccess: isSuccessPostSelectedRushOption,
isLoading: isLoadingPostSelectedRushOption,
fetchData: postSelectedRushOptionApply,
} = useFetch<RushEventStatusCodeResponse, { token: string; optionId: CardOption }>(
({ token, optionId }) => …
```

[Fix] 카드 옵션 선택 시 POST 409 요청 오류

---

admin/src/apis/authAPI.ts
admin/src/apis/imageAPI.ts
admin/src/apis/lotteryAPI.ts
admin/src/apis/rushAPI.ts
admin/src/hooks/useFetchMultiple.ts
admin/src/utils/getMsTime.ts
client/src/apis/authAPI.ts
client/src/apis/linkAPI.ts
client/src/apis/lotteryAPI.ts
client/src/apis/rushAPI.ts
client/src/apis/totalAPI.ts
client/src/hooks/useFetch.ts
client/src/utils/getMsTime.ts
client/src/utils/saveDomImage.ts
client/src/utils/writeClipboard.ts

[Chore] console.error 삭제
