client/src/components/Toggle/index.stories.tsx

[Chore] Toggle Storybook docs 추가

---

client/src/components/Input/index.stories.tsx
client/src/components/Input/index.tsx
client/src/index.css

|light|dark|
|---|---|
|<img width="429" alt="스크린샷 2024-07-24 오후 3 59 39" src="https://github.com/user-attachments/assets/03bfeb24-a6bf-4013-88c1-edd556c8c08e">|<img width="421" alt="스크린샷 2024-07-24 오후 3 59 43" src="https://github.com/user-attachments/assets/9da122a5-177a-41aa-b05e-9d0c6af09faa">|
close #24
- Input 컴포넌트 구현

[Feat] Input 컴포넌트 구현

---

client/src/components/TextField/index.stories.tsx
client/src/components/TextField/index.style.tsx
client/src/components/TextField/index.tsx
client/src/index.css

|small size|large size|
|---|---|
|<img width="417" alt="스크린샷 2024-07-24 오전 11 14 25" src="https://github.com/user-attachments/assets/f2544cd6-b021-483f-b098-e71b18aa0113">|<img width="579" alt="스크린샷 2024-07-24 오전 11 14 30" src="https://github.com/user-attachments/assets/ba902d83-841f-4555-9cfd-653b25d730b7">|
close #11 
- TextField 컴포넌트 구현
```tsx
const requiredTextVariants = cva(`inline`, {
variants: {
isRequired: {
true: "text-s-blue",
},
},
});
```
- cva로 선언된 variants 객체는 다른 파일로 빼는게 깔끔할 것 같기는 한데 그러면 파일이 너무 많아지는 것 같기도 하고,,, 둘다 view를 위한 코드인데 관심사가 너무 분리되는 것 같기도 하고 고민이 되네욤

[Feat] TextField 컴포넌트 구현

---

client/src/components/Keyword/index.stories.tsx
client/src/components/Keyword/index.tsx

[Feat] Keyword 컴포넌트 구현

---

client/src/components/Category/index.stories.tsx
client/src/components/Category/index.tsx

[Feat] Category 컴포넌트 구현

---

client/src/components/Toggle/index.stories.tsx
client/src/components/Toggle/index.tsx

|as-is|to-be|
|---|---|
|<img width="260" alt="스크린샷 2024-07-25 오전 10 55 43" src="https://github.com/user-attachments/assets/8b8675d7-8039-400b-9bf9-0f0788695c93">|<img width="538" alt="스크린샷 2024-07-25 오전 10 55 30" src="https://github.com/user-attachments/assets/4e222254-43c5-4380-9340-57d4d0a4385d">|
close #30

[Fix] Toggle 디자인 수정사항 반영

---

client/src/components/Layout/index.tsx
client/src/pages/BotCustom/index.tsx
client/src/pages/BotCustomResult/index.tsx
client/src/pages/BotShowCase/index.tsx
client/src/pages/Lottery/index.tsx
client/src/pages/Main/index.tsx
client/src/pages/Rush/index.tsx
client/src/router.tsx

[Chore] 라우팅 구조 구축

---

client/src/components/Layout/index.tsx

[Chore] Layout에 헤더 추가

---

client/src/components/Scroll/index.tsx

[Fix] Scroll 기본 스타일 부여

---

client/src/components/CTAButton/index.tsx
client/tsconfig.app.json

없다.
효정님과 함께 해결해보았습니다 :)
close #63

[Fix] 빌드 시 발생한 CTA Button 내부 타입 오류 수정

---

.github/workflows/client_pull_request.yml
.github/workflows/client_push.yml
.github/workflows/pull_request.yml

PR 날린 코드로 빌드에 실패하면 실패 코멘트, 성공하면 성공 코멘트가 달리게 했습니다
close #65

[Chore] 워크플로우 액션 추가

---

client/src/hooks/usePopup.tsx

[Fix] Popup 제출 후 스크롤 방지 삭제

---

client/src/constants/Main/lotteryEventData.ts
client/src/features/Main/Rush.tsx

[Fix] 배포 시 이미지 403 오류 수정

---

client/src/constants/CasperCustom/casper.ts
client/src/constants/CasperShowCase/showCase.ts
client/src/features/CasperShowCase/CasperCards.tsx
client/src/features/CasperShowCase/TransitionCasperCards.tsx
client/src/pages/CasperShowCase/index.tsx

https://github.com/user-attachments/assets/e5dba656-f882-47bc-85e6-ccfb1e0afa7c
close #77
핵심 아이디어는 똑같은 배열 두 개를 붙여서 무한하게 도는 것처럼 보이도록 일종의 트릭을 쓰는 것입니다.
```tsx
const startAnimation = (x: number) => {
leftTransitionControls.start({
x: [x, -totalWidth + x],
transition: CARD_TRANSITION,
});
};
useEffect(() => {
startAnimation(leftX);
}, [transitionControls, totalWidth]);
const stopAnimation = () => {
transitionControls.stop();
if (containerRef.current) {
const computedStyle = window.getComputedStyle(containerRef.current);
const matrix = new WebKitCSSMatrix(computedStyle.transform);
setLeftX(matrix.m41);
}
};
return (
<motion.div
ref={containerRef}
className="flex"
animate={transitionControls}
style={{
gap: `${gap}px`,
}}
onUpdate={(latest) => {
if (parseInt(String(latest.x)) <= -totalWidth) { …
```

[Feat] 캐스퍼 showcase UI 구현

---

client/src/features/CasperShowCase/TransitionCasperCards.tsx

[Fix] context import type 수정

---

client/src/features/CasperCustom/CasperCustomFinish.tsx
client/src/features/CasperCustom/CasperCustomFinishing.tsx
client/src/features/CasperCustom/CasperCustomForm.tsx
client/src/features/CasperCustom/CasperCustomProcess.tsx
client/src/pages/CasperCustom/index.tsx
client/src/pages/CasperCustomResult/index.tsx
client/src/pages/CasperShowCase/index.tsx
client/src/router.tsx

https://github.com/user-attachments/assets/173b32cd-6604-4742-9b4d-a3922d44b3ca
close #93

[Feat] 뱃지 화면 애니메이션 구현

---

.github/workflows/admin_pull_request.yml
.github/workflows/client_pull_request.yml
client/src/features/Lottery/index.tsx

[Fix] Github Action 코멘트 조건 수정

---

client/src/constants/PageSections/sections.ts
client/src/pages/CasperCustom/index.tsx
client/src/pages/CasperShowCase/index.tsx
client/src/types/sections.ts

|캐스퍼 커스텀 페이지|캐스퍼 쇼케이스 페이지|
|---|---|
|<img width="1728" alt="스크린샷 2024-08-08 오후 2 12 59" src="https://github.com/user-attachments/assets/e805ed5a-5a06-43b8-9d58-ef579d2dd3b3">|<img width="1728" alt="스크린샷 2024-08-08 오후 2 13 05" src="https://github.com/user-attachments/assets/6bcab4f6-217b-4e9a-8568-dfe82169482a">|
close #108

[Feat] 캐스퍼 페이지 헤더 반영

---

client/src/features/CasperCustom/CasperCustomFinish.tsx
client/src/features/CasperCustom/CasperCustomFinishing.tsx
client/src/hooks/useBlockNavigation.ts
client/src/pages/CasperCustom/index.tsx
client/src/pages/Lottery/index.tsx
client/src/types/lotteryApi.ts

https://github.com/user-attachments/assets/02bdb862-56e0-4f33-ae23-3bb4ccbabe81
close #122
뒤로가기 confirm 로직을 구현하려고 하는데, history 객체도 못 쓰고 popstate도 제대로 동작하지 않아서 고민하던 중 usePrompt 라는 hook을 발견해서 해당 hook으로 뒤로가기 confirm 로직을 구현했습니다. 
자세한 내용은 [wiki](https://github.com/softeerbootcamp4th/Team7-HybridJGS-FE/wiki/%EB%92%A4%EB%A1%9C%EA%B0%80%EA%B8%B0-confirm-%EB%A1%9C%EC%A7%81-%EA%B5%AC%ED%98%84%ED%95%98%EA%B8%B0)에 적어뒀습니당

[Feat] 뒤로가기/새로고침 방지 구현

---

.github/workflows/admin_pull_request.yml
.github/workflows/client_pull_request.yml

없음
#114 이때 수정했던 사항이 잘못해서 롤백됐는지 수정되어있어서 다시 고쳤습니당

[Fix] action 코멘트 조건 수정

---

admin/package.json
admin/src/components/Layout/index.tsx
admin/src/components/Route/index.tsx
admin/src/hooks/useFetch.ts
admin/src/hooks/useInfiniteFetch.ts
admin/src/pages/ErrorElement/index.tsx
admin/src/pages/NotFound/index.tsx
admin/src/router.tsx
admin/yarn.lock

[Feat] 어드민 - Error handling 구현

---

client/src/features/CasperCustom/CasperCustomFinish.tsx

[Fix] 공유 URL 수정

---

client/src/constants/CasperCustom/casper.ts
client/src/features/CasperCustom/CasperCustomFinishing.tsx

[Feat] 캐스퍼 봇 커스텀 UX/UI 개선

---

client/src/contexts/rushGameContext.tsx

https://github.com/user-attachments/assets/69ca5cef-5ed2-4a29-bc32-11503ea838c7
close #172

[Chore] 카운트 다운 서버 시간으로 변경

---

client/index.html

[Fix] 공유 링크 이미지 뜨게 수정

---

client/src/features/RushGame/RushGameComponents/RushCountdown.tsx
client/src/features/RushGame/RushGameSections/Countdown.tsx
client/src/hooks/RushGame/useSetGamePhase.ts

[Fix] 이벤트 날짜 비교 삭제

---

client/src/features/RushGame/RushGameComponents/RushCardCurrentRatio.tsx

https://github.com/user-attachments/assets/dfae2679-e957-4ffb-a4a8-98d6e04e10a4
close #196

[Fix] 새로고침 딜레이 추가
